name: settlement_detection
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tensorflow
  - tensorboard
  - pydot
  - affine
  - attrs
  - boto3
  - botocore
  - imagecodecs
  - cffi
  - click-plugins
  - cligj
  - cryptography
  - curl
  - docutils
  - freetype
  - gdal
  - geos
  - gettext
  - giflib
  - hdf4
  - hdf5
  - jmespath
  - json-c
  - krb5
  - libdap4
  - libgdal
  - libiconv
  - libkml
  - libnetcdf
  - libpq
  - libspatialite
  - libssh2
  - openjpeg
  - pixman
  - poppler
  - proj
  - pycparser
  - pyopenssl
  - pysocks
  - rasterio
  - s3transfer
  - snuggs
  - sqlite
  - urllib3
  - xerces-c
  - yaml
  - zlib
  - cython
  - pip
  - pip:
    - cachetools
    - chardet
    - cleanlab
    - earthengine-api
    - geojson
    - geomet
    - glob2
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - graphviz
    - html2text
    - httplib2
    - imgaug
    - keras-segmentation
    - memprof
    - opencv-contrib-python-headless
    - opencv-python
    - opencv-python-headless
    - pyasn1
    - pyasn1-modules
    - pycrypto
    - requests
    - rsa
    - scikit-learn
    - sentinelsat
    - tqdm
    - uritemplate
    - utm
